# Generated by Django 5.0.6 on 2024-10-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
