# Generated by Django 5.0.6 on 2024-10-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0003_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
