# Generated by Django 5.0.6 on 2024-10-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0005_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
