# Generated by Django 5.0.6 on 2024-09-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0006_portfoliodetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioDetail',
            new_name='Portfolio',
        ),
    ]
