# Generated by Django 5.0.6 on 2024-10-07 06:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0006_service_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
