# Generated by Django 5.0.6 on 2024-10-07 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0007_quoterequest_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='created_at',
        ),
    ]
