# Generated by Django 5.0.6 on 2024-09-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0007_rename_portfoliodetail_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='card_images/')),
                ('project_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
