# Generated by Django 5.0.6 on 2024-09-23 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0008_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='backendapp.portfolio'),
        ),
        migrations.AddField(
            model_name='card',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='backendapp.project'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='backendapp.project'),
        ),
    ]
