# Generated by Django 5.0.6 on 2024-10-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0008_remove_quoterequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
