# Generated by Django 5.0.6 on 2024-09-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0009_card_portfolio_card_project_portfolio_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='projects',
        ),
    ]
