# Generated by Django 5.0.6 on 2024-09-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0010_remove_portfolio_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='project_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_url',
        ),
    ]
