# Generated by Django 5.0.6 on 2024-09-25 15:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0013_category_tag_postdetail_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetail',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='postdetail',
            name='category',
        ),
        migrations.AlterField(
            model_name='postdetail',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='post_details', to='backendapp.tag'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='backendapp.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='blogs', to='backendapp.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='postdetail',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_details', to='backendapp.category'),
        ),
    ]
