# Generated by Django 5.0.6 on 2024-09-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0014_postdetail_slug_remove_postdetail_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=1, upload_to='blog_images/'),
            preserve_default=False,
        ),
    ]
