# Generated by Django 5.0.6 on 2024-09-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0015_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdetail',
            name='category',
        ),
        migrations.AddField(
            model_name='postdetail',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='post_details', to='backendapp.category'),
        ),
    ]
