# Generated by Django 5.0.6 on 2024-09-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0017_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
